base_url = "https://blog.mggross.com"
compile_sass = true
build_search_index = true
generate_feed = true

title = "Magnus' blog"
description = "My personal blog"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
