base_url = "https://blog.mggross.com"
compile_sass = true
build_search_index = true
generate_feed = true
minify_html = true

title = "Personal blog by Magnus Groß"
description = "My personal blog"

theme = "zola-aurora"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
socials = [
	{ name = "Github", url = "https://github.com/vimpostor" },
]
