base_url = "https://blog.mggross.com"
compile_sass = true
build_search_index = true
generate_feed = true
minify_html = true

title = "Personal blog by Magnus Groß"
description = "My personal blog"

taxonomies = [
	{ name = "tags", feed = true },
]

theme = "zola-aurora"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
menu = [
	{ name = "About", url = "/about" },
	{ name = "Tags", url = "/tags" },
]
socials = [
	{ icon = "github", url = "https://github.com/vimpostor" },
	{ icon = "gitlab", url = "https://gitlab.com/vimpostor" },
]
license = { name = "CC-BY-SA-4.0", url = "https://creativecommons.org/licenses/by-sa/4.0/" }
icons_path = "static/icons/feather/icons"
